image: node

deploy_pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - yarn install
    - yarn run build
  artifacts:
    paths:
      - dist
  only:
    - preproduction
