stages:
  - verify
  - pages

deploy_pages:
  stage: pages
  cache:
    paths:
      - node_modules/
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist
  only:
    - preproduction
