image: node

before_script:
  - npm install

deploy_pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - npm run build
  artifacts:
    paths:
      - dist
  only:
    - preproduction
